### ISSUE TITLE
Numba Tesselate Error

### ISSUE THREAD

**Issue by smh2287** [alessandro-zomparelli/tissue#119]
I cannot use numba tesselate due to an error 
![image](https://user-images.githubusercontent.com/57993768/124534084-8380be00-de4e-11eb-98ff-027d3b96df3c.png)

It works without numba.

![image](https://user-images.githubusercontent.com/57993768/124534136-985d5180-de4e-11eb-9101-f3ee85e90fab.png)

but does not work when numba tesselation is turned on

**Comment by alessandro-zomparelli** [comment]
hi @smh2287 
Are you using the stable Blender 2.93 or an old beta version?
I'm not able to reproduce your error. Does it happen every time that you tessellate something?
Can you please show me a screenshot of the console? Is there any other message?

**Comment by smh2287** [comment]
actually. it got fixed by itself. I too cannot reproduce the error right now. everything is fine I guess.. will notice you next time if this error happens again

**Comment by inca** [comment]
Not sure if it's the same issue, I've got `numba_interp_points` is not defined.

```
Error: Python: Traceback (most recent call last):
  File "...\Blender\2.93\scripts\addons\tissue\dual_mesh.py", line 131, in execute
    bpy.ops.object.tissue_update_tessellate()
  File "...\Blender\2.93\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "...\Blender\2.93\scripts\addons\tissue\tessellate_numpy.py", line 2059, in execute
    same_iteration = tessellate_patch(tess_props)
  File "...\Blender\2.93\scripts\addons\tissue\tessellate_numpy.py", line 726, in tessellate_patch
    co2 = np_lerp2(v00, v10, v01, v11, vx, vy, 'verts')
  File "...\Blender\2.93\scripts\addons\tissue\utils.py", line 96, in np_lerp2
    co2 = numba_interp_points(v00, v10, v01, v11, vx, vy)
NameError: name 'numba_interp_points' is not defined
```

I am using Blender 2.93.2 and Tissue 0.3.50

**Comment by prubini87** [comment]
Same error here, Blender 2.93.4

**Comment by prubini87** [comment]
> Same error here, Blender 2.93.4

Restarting Blender has fixed it for me. It was my first time running it, on a fresh Windows installation.

**Comment by onerawartist** [comment]
never use the one that comes with blender , its outdated and always has been, i dont know why lol so i never use that, i always use the one here on github
