### ISSUE TITLE
i got a new laptop and tissue showing me an error i never saw before

### ISSUE THREAD

**Issue by onerawartist** [alessandro-zomparelli/tissue#129]
![01](https://user-images.githubusercontent.com/71472224/147850022-e9cf38be-4e79-4f4c-a53d-cf4fe28f70f5.png)

.............................
 and when i go to console i see this 
 ......................
 Read prefs: C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend
bpy.utils.register_tool: could not find 'after' {'BoxCutter'}
bpy.utils.register_tool: could not find 'after' {'BoxCutter'}
HardOps 0.9.87.26 available!
Registered MACHIN3tools 0.9.0 with 0 tools, 2 pie menus
CAD Transform 0.93.2 : ready
addon_utils.disable: tissue-0-3-51 not disabled
addon_utils.disable: tissue-0-3-51 not disabled
Modules Installed (tissue-0-3-51) from 'C:\\Users\\LEGION 5\\Desktop\\New folder\\tissue-0-3-51.zip' into 'C:\\Users\\LEGION 5\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\startup\bl_ui\space_userpref.py", line 2055, in draw    draw(context)
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\config.py", line 29, in draw
    Pip._ensure_user_site_package()
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\utils_pip.py", line 47, in _ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\startup\bl_ui\space_userpref.py", line 2055, in draw    draw(context)
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\config.py", line 29, in draw
    Pip._ensure_user_site_package()
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\utils_pip.py", line 47, in _ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\startup\bl_ui\space_userpref.py", line 2055, in draw    draw(context)
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\config.py", line 29, in draw
    Pip._ensure_user_site_package()
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\utils_pip.py", line 47, in _ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\startup\bl_ui\space_userpref.py", line 2055, in draw    draw(context)
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\config.py", line 29, in draw
    Pip._ensure_user_site_package()
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\utils_pip.py", line 47, in _ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\startup\bl_ui\space_userpref.py", line 2055, in draw    draw(context)
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\config.py", line 29, in draw
    Pip._ensure_user_site_package()
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\utils_pip.py", line 47, in _ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\startup\bl_ui\space_userpref.py", line 2055, in draw    draw(context)
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\config.py", line 29, in draw
    Pip._ensure_user_site_package()
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\utils_pip.py", line 47, in _ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\startup\bl_ui\space_userpref.py", line 2055, in draw    draw(context)
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\config.py", line 29, in draw
    Pip._ensure_user_site_package()
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\utils_pip.py", line 47, in _ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\startup\bl_ui\space_userpref.py", line 2055, in draw    draw(context)
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\config.py", line 29, in draw
    Pip._ensure_user_site_package()
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\utils_pip.py", line 47, in _ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\startup\bl_ui\space_userpref.py", line 2055, in draw    draw(context)
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\config.py", line 29, in draw
    Pip._ensure_user_site_package()
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\utils_pip.py", line 47, in _ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\startup\bl_ui\space_userpref.py", line 2055, in draw    draw(context)
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\config.py", line 29, in draw
    Pip._ensure_user_site_package()
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\utils_pip.py", line 47, in _ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\startup\bl_ui\space_userpref.py", line 2055, in draw    draw(context)
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\config.py", line 29, in draw
    Pip._ensure_user_site_package()
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\utils_pip.py", line 47, in _ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\startup\bl_ui\space_userpref.py", line 2055, in draw    draw(context)
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\config.py", line 29, in draw
    Pip._ensure_user_site_package()
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\utils_pip.py", line 47, in _ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\startup\bl_ui\space_userpref.py", line 2055, in draw    draw(context)
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\config.py", line 29, in draw
    Pip._ensure_user_site_package()
  File "C:\Users\LEGION 5\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\tissue-0-3-51\utils_pip.py", line 47, in _ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given

**Comment by onerawartist** [comment]
the new laptop has an AMD ryzen 5 and an RTX 3060 , do i need to install something ?

**Comment by onerawartist** [comment]
![02](https://user-images.githubusercontent.com/71472224/147850178-28e3171f-96d7-4b01-9eae-040c225f2d15.png)


i tried 3.0 and still the same problem, i know its my laptop problem , can anyone help ?

**Comment by onerawartist** [comment]
and im on blender 3.0

**Comment by alessandro-zomparelli** [comment]
Hi, I'm sorry for my late reply. I never had this problem, but you can try this version: https://github.com/alessandro-zomparelli/tissue/releases/tag/v0-3-52
On the release 3.0.1 of Blender 3.0.1.

Tissue 0.3.52 is also shipped with the development build of Blender 3.1, but I realized that Blender 3.1 is using a new version of Numba that is no supported yet by Numba. It will work, but it could be a bit slower, especially the Reaction-Diffusion.

**Comment by alessandro-zomparelli** [comment]
Hi @onerawartist I think that the issue should be resolved with the latest commit to the master branch: https://github.com/alessandro-zomparelli/tissue
