### ISSUE TITLE
Tesselate 2 planes as a single object on a torus

### ISSUE THREAD

**Issue by Piergiorgio-PG** [alessandro-zomparelli/tissue#143]
Hi there! 

I was trying to tesselate 2 planes as a single object on a torus and I ran into an issue

Tissue version 0.3.52
 **System Information**
Operating system: macOS-12.6.2-arm64-arm-64bit 64 Bits
Graphics card: Apple M1 Max Apple 4.1 Metal - 76.3

**Blender Version**
Broken: version: 3.4.0, branch: blender-v3.4-release, commit date: 2022-12-06 18:46, hash: `rBa95bf1ac01be`
Worked: (newest version of Blender that worked as expected)

Error: Python: Traceback (most recent call last):
  File "/Applications/Blender_3.4.app/Contents/Resources/3.4/scripts/addons/mesh_tissue/tessellate_numpy.py", line 2080, in execute
    same_iteration = tessellate_patch(tess_props)
  File "/Applications/Blender_3.4.app/Contents/Resources/3.4/scripts/addons/mesh_tissue/tessellate_numpy.py", line 738, in tessellate_patch
    co2 = np_lerp2(v00, v10, v01, v11, vx, vy, 'verts')
  File "/Applications/Blender_3.4.app/Contents/Resources/3.4/scripts/addons/mesh_tissue/utils.py", line 80, in np_lerp2
    co2 = numba_interp_points(v00, v10, v01, v11, vx, vy)
NameError: name 'numba_interp_points' is not defined
Location: /Applications/Blender_3.4.app/Contents/Resources/3.4/scripts/modules/bpy/ops.py:113

THX

**Comment by Piergiorgio-PG** [comment]
Here I'm again :) I downloaded the last version 0.3.54 and now everything works as expected :) THX
