### ISSUE TITLE
Tissue not installing on MacOS 

### ISSUE THREAD

**Issue by laffan** [alessandro-zomparelli/tissue#151]
Hi there - I'm really excited to try this out, but am getting the following console error message on MacOS when I try to install tissue. I'm using Blender 3.6.1 and MacOS 13.5.1.

```
METAL API - DETECTED GPU: Apple M2 Max
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/startup/bl_ui/space_userpref.py", line 2138, in draw
    draw(context)
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/addons/mesh_tissue/config.py", line 31, in draw
    Pip._ensure_user_site_package()
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/addons/mesh_tissue/utils_pip.py", line 27, in _ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/startup/bl_ui/space_userpref.py", line 2138, in draw
    draw(context)
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/addons/mesh_tissue/config.py", line 31, in draw
    Pip._ensure_user_site_package()
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/addons/mesh_tissue/utils_pip.py", line 27, in _ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/startup/bl_ui/space_userpref.py", line 2138, in draw
    draw(context)
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/addons/mesh_tissue/config.py", line 31, in draw
    Pip._ensure_user_site_package()
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/addons/mesh_tissue/utils_pip.py", line 27, in _ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/startup/bl_ui/space_userpref.py", line 2138, in draw
    draw(context)
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/addons/mesh_tissue/config.py", line 31, in draw
    Pip._ensure_user_site_package()
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/addons/mesh_tissue/utils_pip.py", line 27, in _ensure_user_site_package
    site_package = bpy.utils.user_resource('SCRIPTS', "site_package", create=True)
TypeError: user_resource() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given

```

**Comment by laffan** [comment]
Well, never mind. I'm going to leave this here in case other people run in to the same issue, but using the appropriate dev branch - https://github.com/alessandro-zomparelli/tissue/tree/b360-dev - solved my problem. Thank you for making Tissue!
