### ISSUE TITLE
Numba not installing

### ISSUE THREAD

**Issue by JoelGodin** [alessandro-zomparelli/tissue#85]
Tried to install 0.3.48 and am getting this error:
![11](https://user-images.githubusercontent.com/9205295/100516354-4f734b00-3151-11eb-9240-ba3ba41647ae.png)
I hit install, it installed something (from that popup) and then tried install numba and it turned blue for a moment, and then nothing.  Still says numba has to be installed.
I used to have Xcode, but recently had a hard drive crash and did a new install on an SSD.
Now I can't install Xcode because is says I need 10.15 or newer.  
I have 10.13 and can't install any newer macOS's.
Do I really need Xcode to install numba?

**Comment by JoelGodin** [comment]
Looks like dev tools is installed:
![1](https://user-images.githubusercontent.com/9205295/100516697-a417c580-3153-11eb-813d-b6f790ec4d71.png)

**Comment by JoelGodin** [comment]
Just read that is it mostly for Reaction-Diffusion which I don't use, so no urgency on my part.

**Comment by alessandro-zomparelli** [comment]
Hi @JoelGodin , yes, I can confirm that it is currently used only for the Reaction-Diffusion.
Unfortunately, I don't know the macOS, and I really don't know how to fix that. 
@s-leger you helped me with that before, any chance that you know what is happening? Thanks

**Comment by s-leger** [comment]
As far as i can tell, a precompiled version of numba for python 3.7 may not be available for macOS, so the pip installer download source and must compile on the fly.
Pip run using "--only-binary all" option by default, meaning it should only download binary when available and may fallback to source when not available.

**Comment by alessandro-zomparelli** [comment]
Hi @s-leger thanks :-) Do you have any possible solution to suggest?

**Comment by s-leger** [comment]
Pip class should be verbose enougth to provide a reason for failure to install pre-compiled version, maybe a missing dep issue (as by default it does not try to solve such deps  --no-deps argument)
Any console log of failed setup may help to narrow down the issue on macOS - maybe missing llvmlite 0.34.*

**Comment by JoelGodin** [comment]
I am seeing this:

[image: 2.png]


nw_path_close_fd Failed to close guarded necp fd 6 [9: Bad file descriptor]

**Comment by JoelGodin** [comment]
![2](https://user-images.githubusercontent.com/9205295/100553879-c64a3a00-325e-11eb-9a59-8b0afa0ec2c4.png)

Image 2 reuploaded.

**Comment by s-leger** [comment]
open blender and from a console, run (assuming tissue folder is "tissue-master")
```python
from tissue-master.utils_pip import Pip
Pip.install("numba") 
```
You should see a brunch of pip related lines on the console.

**Comment by JoelGodin** [comment]
I got this:

>>> from tissue-b290-dev0.3.48.utils_pip import Pip
  File "<blender_console>", line 1
    from tissue-b290-dev0.3.48.utils_pip import Pip
               ^
SyntaxError: invalid syntax

>>> Pip.install("numba")
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
NameError: name 'Pip' is not defined

>>>

**Comment by s-leger** [comment]
Ok,
pay attention at removing every "." in the folder name, could also be an issue for blender - this is not allowed by python - !

**Comment by JoelGodin** [comment]
Like this:

>>> from tissue-b290-dev0348utils_pip import Pip
  File "<blender_console>", line 1
    from tissue-b290-dev0348utils_pip import Pip
               ^
SyntaxError: invalid syntax

>>> from tissueb290dev038utils_pip import Pip
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
ModuleNotFoundError: No module named 'tissueb290dev038utils_pip'

>>>

**Comment by s-leger** [comment]
Rename the folder itself, removing dot in folder name.
then 
```python
from your_new_folder_name.utils_pip import Pip
```

**Comment by JoelGodin** [comment]
Screen shot here:
![11](https://user-images.githubusercontent.com/9205295/100555794-f0562900-326b-11eb-9710-1514c9fbd1cc.png)

**Comment by JoelGodin** [comment]
oops, I see what I did. Hold on.

**Comment by JoelGodin** [comment]
Okay, I get this 
>>> from tissueb290dev0348.utils_pip import Pip
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
ModuleNotFoundError: No module named 'tissueb290dev0348'

**Comment by s-leger** [comment]
When you setup on macOS it does unzip into (assuming you are using default settings to setup your addons)
/Users/$USER/Library/Application Support/Blender/2.91/scripts/addons/tissue-xxx
You must use that folder name for the command, and ensure the folder name does not contains any "." in the between.

**Comment by JoelGodin** [comment]
Get this
![22](https://user-images.githubusercontent.com/9205295/100556070-88084700-326d-11eb-9e12-391a0e1bad26.png)

**Comment by s-leger** [comment]
hmm looks like it also did not like the "-" in the names.

**Comment by JoelGodin** [comment]
Okay, removed, recompressed, went okay, this from second command:
>>> from tissueb290dev.utils_pip import Pip
>>> Pip.install("numba")
Collecting numba

  Using cached https://files.pythonhosted.org/packages/5e/81/6fd1dd064bcf71a79da109e8966a39e2da61d68bf0bd1e0839fa997f8c41/numba-0.51.2.tar.gz

Installing collected packages: numba

  Running setup.py install for numba: started

    Running setup.py install for numba: finished with status 'error'

(False, '')

**Comment by s-leger** [comment]
Ok, may miss llvmlite
Try
Pip.install("llvmlite")
and then the numba setup.

**Comment by JoelGodin** [comment]
>>> Pip.install("llvmlite")
Requirement already satisfied: llvmlite in /Users/joelgodin/.local/lib/python3.7/site-packages (0.34.0)

(False, '')

>>> Pip.install("numba")
Collecting numba

  Using cached https://files.pythonhosted.org/packages/5e/81/6fd1dd064bcf71a79da109e8966a39e2da61d68bf0bd1e0839fa997f8c41/numba-0.51.2.tar.gz

Installing collected packages: numba

  Running setup.py install for numba: started

    Running setup.py install for numba: finished with status 'error'

(False, '')

>>>

**Comment by s-leger** [comment]
Hmm, with such "usefull" status report will be pretty hard to figure what the issue realy is.
As far as i can tell there is no "wheel" available and it still expect xcode in order to build.
Maybe you should ask on numba mailing list.

**Comment by JoelGodin** [comment]
ok, thanks for your help on this.

**Comment by JoelGodin** [comment]
@s-leger Just wanted to ask first, "As far as i can tell, a precompiled version of numba for python 3.7 may not be available for macOS, so the pip installer download source and must compile on the fly."
I have python 2.7.16
Would that be the issue?

**Comment by s-leger** [comment]
Blender should use her own python interpreter.
You should see the version number in the blender's python console.

Numba require
* Python versions: 3.6-3.8
* llvmlite 0.34.*
* NumPy >=1.15 (can build with 1.11 for ABI compatibility)
Optionally:
* Scipy >=1.0.0 (for ``numpy.linalg`` support)

**Comment by JoelGodin** [comment]
I see.
I'm going to try and download Xcode first.
I had a hard drive crash and this is a new drive.
I had numba working on my last hard drive. It had Xcode installed.
